# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

MR_EM <- function(K, initVals, X, Y, seX, seY, Nstart_MC = 500L, equalSds = FALSE, M = 4L, max_Nsamples = 500000L, min_iters = 2L, max_iters = 100L, alpha = 0.05, gamma = 0.05, eps = 0.005, verbose = FALSE, saveTraj = FALSE, computeSE = TRUE) {
    .Call(`_MR_MCEM_MR_EM`, K, initVals, X, Y, seX, seY, Nstart_MC, equalSds, M, max_Nsamples, min_iters, max_iters, alpha, gamma, eps, verbose, saveTraj, computeSE)
}

sampleLatentVarPost <- function(N_samples, X, Y, seX, seY, params) {
    .Call(`_MR_MCEM_sampleLatentVarPost`, N_samples, X, Y, seX, seY, params)
}

