# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

MR_PATH <- function(K, data, initVals, overDispersedY = FALSE, equalSds = FALSE, computeSE = TRUE, Nstart_MC = 500L, M = 4L, max_Nsamples = 500000L, min_iters = 2L, max_iters = 100L, alpha = 0.05, gamma = 0.05, eps = 0.005, verbose = FALSE, saveTraj = FALSE) {
    .Call(`_MRPATH_MR_PATH`, K, data, initVals, overDispersedY, equalSds, computeSE, Nstart_MC, M, max_Nsamples, min_iters, max_iters, alpha, gamma, eps, verbose, saveTraj)
}

getImportanceSamples <- function(data, MCEM_fit, Nsamples = 50000L) {
    .Call(`_MRPATH_getImportanceSamples`, data, MCEM_fit, Nsamples)
}

